name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux, android]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run Tests
        run: flutter test || echo "No tests found or test failed"

      - name: Build Android APK
        if: matrix.platform == 'android'
        run: flutter build apk --release --obfuscate --split-debug-info=./debug_info

      - name: Upload APK
        if: matrix.platform == 'android'
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
